apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: cp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=oidc
            - --redirect-url=https://oauth2.internal.dev.cloud.jumbo.com/oauth2/callback
            - --oidc-issuer-url=https://dev-22399512.okta.com/oauth2/default
            - --cookie-secret=thisIsARandomCookieSecre
            - --email-domain=*
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --skip-provider-button=true
            - --cookie-secure=false
            - --pass-access-token=true
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: 0oawgkwqqaYoPI73z5d6
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: 4Da-MuuEz6W0oB_U4Ud07r1KPJrij4bZ_-U3jrLt
            - name: OAUTH2_PROXY_COOKIE_DOMAINS
              value: ".jumbo.com"
            - name: OAUTH2_PROXY_SET_XAUTHREQUEST
              value: "true"
            - name: "OAUTH2_PROXY_WHITELIST_DOMAINS"
              value: ".jumbo.com"
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP