FROM openjdk:11.0.11-jdk
RUN apk add htop curl vim tree

RUN wget https://www.yourkit.com/download/docker/YourKit-JavaProfiler-2019.1-docker.zip -P /tmp/ && \
  unzip /tmp/YourKit-JavaProfiler-2019.1-docker.zip -d /usr/local && \
  rm /tmp/YourKit-JavaProfiler-2019.1-docker.zip

RUN apk add --no-cache libc6-compat
RUN apk add --no-cache gcompat

RUN echo 'alias ll="ls -al" \
        alias l="ll"' >> /root/.profile
RUN mkdir -p /opt/app
COPY ./target/dojodockerapp.jar /opt/app/dojodockerapp.jar
ARG JDK8_STUFF="-Djava.security.egd=file:/dev/./urandom -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -agentpath:/usr/local/YourKit-JavaProfiler-2019.1/bin/linux-x86-64/libyjpagent.so=port=10001,listen=all"
ARG DEFAULT_JAVA_OPTS="-Xms256m -Xmx512m $JDK8_STUFF"
ENV JAVA_OPTS=$DEFAULT_JAVA_OPTS
ENTRYPOINT java $JAVA_OPTS  -jar /opt/app/dojodockerapp.jar
EXPOSE 10001 8080

# docker build -t bla:1.0 -f Dockerfile-forTraceAlpine .
# docker run -d -it -p 8080:8080 -p 10001:10001 bla:1.0