apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: dojodocker-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /ingress/?(.*)
          backend:
            serviceName: dojo-service
            servicePort: 80